services:
  postgres:
    image: postgres:16-alpine
    container_name: express_api_postgres
    ports:
      - '5500:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
