services:
  postgres:
    image: postgres:16-alpine
    container_name: dev_express_server_db
    ports:
      - '5500:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express_api_db
    volumes:
      - dev_express_server_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d express_api_db']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dev_express_server_postgres_data:
